/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/app-bar/AppBar.vue')['default']
    AppDrawer: typeof import('./src/components/app-drawer/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/app-footer/AppFooter.vue')['default']
    AuthDialog: typeof import('./src/components/auth/AuthDialog.vue')['default']
    BaseSongCard: typeof import('./src/components/song-card/BaseSongCard.vue')['default']
    BottomMenu: typeof import('./src/components/bottom-menu/BottomMenu.vue')['default']
    PlaylistCard: typeof import('./src/components/playlist-card/PlaylistCard.vue')['default']
    PlaylistFormDialog: typeof import('./src/components/playlist-form/PlaylistFormDialog.vue')['default']
    PlaylistSongCard: typeof import('./src/components/song-card/PlaylistSongCard.vue')['default']
    PlaylistSongList: typeof import('./src/components/playlist-song-list/PlaylistSongList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableText: typeof import('./src/components/utils/ScrollableText.vue')['default']
    SearchArea: typeof import('./src/components/search-area/SearchArea.vue')['default']
    ShareYoutube: typeof import('./src/components/share-youtube/ShareYoutube.vue')['default']
    SongCard: typeof import('./src/components/song-card/SongCard.vue')['default']
    YoutubePlayer: typeof import('./src/components/youtube-player/YoutubePlayer.vue')['default']
  }
}
